### ISSUE TITLE
Web app

### ISSUE THREAD

**Issue by JulianWgs** [SafeMarket-WirVsVirus/frontend-enduser#93]
Hello,

I'm from the team which also participated in the same category in WirvsVirus hackathon. We've created [WeQueue](https://devpost.com/software/01_771_supermarktstatus_digitalewarteschlange) project.

We decided early on that ease of use is one of the main criteria for the app. Only a web application can offer that, because no installation or account is required. Just like a waiting line in the real world.

Is there something like that planned? I'm glad to help :)

Best greetings
Julian

**Comment by juliaringler** [comment]
Hi @JulianWgs,

At the moment we discuss the supported features in the "Anforderungspezifikation" document (please check discord or trello for the link to this document). I guess this it the correct place to address this and afterwards we should decide which technology we should choose to support all requested features and use cases ;)

For the MVP we want to deliver in the next two weeks, we put web on-hold and wanted to get started with the existing app solution before supporting web (Erik already gave flutter-web a quick glance).

Our assumption at the moment is that if we add web support, we should also support that the user can switch the device seamlessly. This would require some kind of account management which is out of scope for the MVP.

Having said that: We are always happy if you want to contribute :) At the moment this project is flutter only but the retail solution uses vue.js and might switch to another technology in the future since the people, who started it, left the project.

**Comment by juliaringler** [comment]
For the MVP the web app is out of scope, closing this ticket for now.
